### ISSUE TITLE
Upgrade basic hessian version to v4.0.51.

### ISSUE THREAD

**Issue by ujjboy** [alipay/sofa-hessian#12]
There are lots of guys using hessian 4.x in their project, and they want to use it in `sofa-rpc`, and it will incompatible with `sofa-hessian` (base on hessian v3.1.3, and support generic invoke and security enhancement). 

I will start v4.0.0 milestone, and make the `sofa-hessian` based on lasted stable version  [hessian-4.0.51](http://hessian.caucho.com/#Java), and also support generic invoke and security enhancement.

**Comment by leizhiyuan** [comment]
release 一个正式版?

**Comment by leizhiyuan** [comment]
hessian will be available only in jdk8?
