### ISSUE TITLE
和hessian4比较有哪些优势

### ISSUE THREAD

**Issue by Viyond** [alipay/sofa-hessian#6]
如题，请问里面部分修复或者优化的问题在hessian4是否已经解决了，或者相比hessian4有什么好的特点吗，比方说使用hessian4的用户还有必要尝试你这个版本吗，谢谢。

**Comment by ujjboy** [comment]
在蚂蚁内部 SOFAHessian3 已经大规模使用，而 Hessian3 和 Hessian4 在协议上还是有不兼容的地方，所以我们是基于 Hessian 3 进行发展。

[改进点](https://github.com/alipay/sofa-hessian/wiki/Improvements)中的 Bug Fix 部分我相信 Hessian4 已经修复，锁优化 Hessian4 也已经优化了一部分，但是其它安全、泛化等特性 Hessian4 肯定是没有的。

你可以试用下，如果你感兴趣但是你更倾向于 Hessian4，我们非常欢迎一起共建一个基于 Hessian 4 的 SOFA Hessian 版本。

**Comment by leizhiyuan** [comment]
那这个 issue, 先暂时关闭了.
