### ISSUE TITLE
Fix some security vulnerabilities

### ISSUE THREAD

**Issue by leizhiyuan** [alipay/sofa-hessian#7]
https://github.com/mbechler/marshalsec/blob/master/marshalsec.pdf

from the paper, we can know there are some vulnerabilities when Unmarshall hessian

https://github.com/mbechler/marshalsec

we have provided some filters in 

```
com.caucho.hessian.io.Hessian2Input#readObjectDefinition
```

com.alipay.hessian.internal.InternalNameBlackListFilter is a filter which contains classes which have vulnerabilities to hacking.

what we need to do is add more classes which have vulnerabilities to the list that provided from our security team.

**Comment by khotyn** [comment]
这个问题没有任何具体的描述吗？

**Comment by leizhiyuan** [comment]
更新了下.
